### ISSUE TITLE
现在有很多免费的 https docker 部署的云服务商，我觉你可以搞个一件部署

### ISSUE THREAD

**Issue by mokeyish** [PikuZheng/smartdns-rs#12]
制作 docker 可以读取环境变量，下载配置文件的镜像

部署的时候配置一下
- 配置文件的 url 地址(比如 github 仓库的文件路径上的)
- 下载配置文件
- 启动 https 服务。

这就可以通过一些云服务商，从 github 仓库里的配置文件，快速起一个自己的 DoH 服务。

**Comment by PikuZheng** [comment]
没理解 现在这边是自动编译然后推送到hub.docker.com的
我自己在vps用unbound

**Comment by mokeyish** [comment]
比如 https://render.com/ ，它支持加载自己的镜像。制作 smartdns 镜像，这不就可以部署一个私有的 DoH 服务器了么。

**Comment by PikuZheng** [comment]
没有必要。。。咱有vps用
